### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by nineosis** [NotCookey/OniAnimeDownloader#1]
Python 2.7 gives a syntax error on line 18 at def.
Python 3.10 gives missing module "aiohttp"
can you add a requirements.txt or a bit of depth to operation?

**Comment by NotCookey** [comment]
> 

I recommend using Python 3.6 or above.
And yes my bad i didn't upload a requirements info i will do it as well.
For now this are the requirements -
```
PyQt5
aiohttp
bs4
asyncio
os
requests
webbrowser
```
